node {
    def commit_id
    stage('Preparation') {
        checkout scm
        bat 'git rev-parse --short HEAD' > '.git/commit_id'
        commit_id = readFile('.git/commit_id').trim()
    }

    stage('test') {
        nodejs(installationName: 'nodejs') {
            bat 'npm install --only=dev'
            bat 'npm test'
        }
    }

     stage('docker build/push') {
        docker.withRegistry('https://index.docker.io/v2/', 'dockerhub') {
        def app = docker.build("nishant1529/docker-nodejs-demo:${commit_id}", '.').push()
        }
   }
}
