node {
    def commit_id

    stage('Preparation') {
        checkout scm

        commit_id = bat(
            script: 'git rev-parse --short HEAD',
            returnStdout: true
        ).trim()

        echo "Commit ID: ${commit_id}"
    }

    stage('Test') {
        nodejs(installationName: 'nodejs') {
            bat 'npm ci'
            bat 'npm test'
        }
    }

    stage('Build') {
        nodejs(installationName: 'nodejs') {
            bat 'npm ci --omit=dev'
            archiveArtifacts artifacts: 'package*.json,app.js', fingerprint: true
        }
    }
}